### ISSUE TITLE
Losing dataSource on ResolveDataSource

### ISSUE THREAD

**Issue by the1alt** [conceptadev/typeorm-seeding#3]
Hi, 

I'm trying to use this package, using rockets-starter to understand it.
Each time I try to seed datas, I have this error message : 

`
Cannot read properties of undefined (reading 'name')
    at new DataSource (/Users/piman/Sites/manitude/node_modules/typeorm/data-source/DataSource.js:46:29)
    at Object.resolveDataSource (/Users/piman/Sites/manitude/node_modules/@concepta/typeorm-seeding/dist/utils/resolve-data-source.js:8:90)
`

It seems that the object dataSource from 'this.options' is not accessible inside of the resolveDataSource function, even through it exists in the get dataSource()'s function of the seeding-source.js;

Or maybe I'm not creating my seedingSource object correctly.

_seeding.ts_
```javascript
import { ApiConfigService } from "./common/api-config/api.config.service";

const { config } = require('dotenv');
const { SeedingSource } = require('@concepta/typeorm-seeding');
const { AppSeeder } = require('./app.seeder');
const { default: DataSource } = require('./ormconfig');

config();

const options = {
  DataSource,
  seeders: [AppSeeder],
  defaultSeeders: [AppSeeder],
}

module.exports =  new SeedingSource(options);
```

_ormconfig.ts_
```javascript
import { DataSource } from 'typeorm';
import { ormConfigFactory } from './common/api-config/typeorm.config';

const source = new DataSource({
  ...ormConfigFactory()
});

export default source;
```

_typeorm.config.ts_
```javascript
import { DataSourceOptions } from 'typeorm';
import { registerAs } from '@nestjs/config';

export const ormConfigFactory = (): DataSourceOptions => {
  return {
    migrationsTableName: 'migrations',
    name: 'default',
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'myname',
    password: 'mypassword',
    database: 'mydb',
    logging: false,
    synchronize: false,
    entities: ['src/endpoints/**/**.entity{.ts,.js}'],
    migrations: ['dist/migration/**/*{.ts,.js}'],
  };
};

export const ormConfig = registerAs('TYPEORM_MODULE_CONFIG', ormConfigFactory);
```

_plackage.json scripts_
```javascript
"seed:config": "typeorm-seeding config -r ./dist -c src/seeding.js",
    "seed:run": "typeorm-seeding seed -r ./dist -c src/seeding.js"
```

![image](https://user-images.githubusercontent.com/23243276/201897301-5c379bdf-87ff-4109-b7b2-bd13199b4b8d.png)

![image](https://user-images.githubusercontent.com/23243276/201897395-8274de59-3f62-4c61-be5b-5479d99bac58.png)

**Comment by MrMaz** [comment]
I apologize for not responding, I was out on vacation and I am just catching up. Did you ever find the solution on your own, or do you still need help?

**Comment by the1alt** [comment]
Hi, i switched to an older version of type-orm
If you find the solution it could be great

**Comment by MrMaz** [comment]
@the1alt can you provide a repo that reproduces the issue? it may be as simple as configuration.
